-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-09 00:41:56 IST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Amenity 
    (
     AmenityID INTEGER NOT NULL , 
     AmenityName VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Amenity ADD CONSTRAINT Amenity_PK PRIMARY KEY CLUSTERED (AmenityID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Booking 
    (
     BookingID INTEGER NOT NULL , 
     BookingDate DATE NOT NULL , 
     StartTime TIME NOT NULL , 
     EndTime TIME NOT NULL , 
     Status VARCHAR (20) NOT NULL , 
     Member_MemberID INTEGER NOT NULL , 
     Facility_FacilityID INTEGER NOT NULL 
    )
GO

ALTER TABLE Booking ADD CONSTRAINT Booking_PK PRIMARY KEY CLUSTERED (BookingID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Facility 
    (
     FacilityID INTEGER NOT NULL , 
     FacilityName VARCHAR (100) NOT NULL , 
     FacilityType VARCHAR (50) NOT NULL , 
     FacilityLocation VARCHAR (100) NOT NULL , 
     FacilityCapacity INTEGER NOT NULL , 
     FacilityAvailabilityStatus VARCHAR (20) NOT NULL , 
     StatusReason VARCHAR (255) , 
     Description VARCHAR (500) NOT NULL , 
     OpeningTime TIME NOT NULL , 
     ClosingTime TIME NOT NULL 
    )
GO

ALTER TABLE Facility ADD CONSTRAINT Facility_PK PRIMARY KEY CLUSTERED (FacilityID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FacilityAmenity 
    (
     Facility_FacilityID INTEGER NOT NULL , 
     Amenity_AmenityID INTEGER NOT NULL 
    )
GO

ALTER TABLE FacilityAmenity ADD CONSTRAINT FacilityAmenity_PK PRIMARY KEY CLUSTERED (Facility_FacilityID, Amenity_AmenityID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FacilitySport 
    (
     Facility_FacilityID INTEGER NOT NULL , 
     Sport_SportID INTEGER NOT NULL 
    )
GO

ALTER TABLE FacilitySport ADD CONSTRAINT FacilitySport_PK PRIMARY KEY CLUSTERED (Facility_FacilityID, Sport_SportID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Inquiry 
    (
     InquiryID INTEGER NOT NULL , 
     Name VARCHAR (100) NOT NULL , 
     Email VARCHAR (100) NOT NULL , 
     ContactNo VARCHAR (15) NOT NULL , 
     InquiryMessage VARCHAR (500) NOT NULL , 
     InquiryDate DATE NOT NULL , 
     Facility_FacilityID INTEGER 
    )
GO

ALTER TABLE Inquiry ADD CONSTRAINT Inquiry_PK PRIMARY KEY CLUSTERED (InquiryID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Member 
    (
     MemberID INTEGER NOT NULL , 
     MemberName VARCHAR (100) NOT NULL , 
     MemberPhoneNumber VARCHAR (15) NOT NULL , 
     MemberEmail VARCHAR (100) NOT NULL , 
     MemberAddress VARCHAR (255) NOT NULL , 
     MemberPassword VARCHAR (255) NOT NULL , 
     DateRegistered DATE NOT NULL 
    )
GO

ALTER TABLE Member ADD CONSTRAINT Member_PK PRIMARY KEY CLUSTERED (MemberID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MemberSports 
    (
     Member_MemberID INTEGER NOT NULL , 
     Sport_SportID INTEGER NOT NULL 
    )
GO

ALTER TABLE MemberSports ADD CONSTRAINT MemberSports_PK PRIMARY KEY CLUSTERED (Member_MemberID, Sport_SportID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Payment 
    (
     PaymentID INTEGER NOT NULL , 
     Amount DECIMAL (10,2) NOT NULL , 
     PaymentDate DATE NOT NULL , 
     PaymentMethod VARCHAR (50) NOT NULL , 
     PaymentStatus VARCHAR (50) NOT NULL , 
     Booking_BookingID INTEGER NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    Payment__IDX ON Payment 
    ( 
     Booking_BookingID 
    ) 
GO

ALTER TABLE Payment ADD CONSTRAINT Payment_PK PRIMARY KEY CLUSTERED (PaymentID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Review 
    (
     ReviewID INTEGER NOT NULL , 
     Rating INTEGER NOT NULL , 
     Comment VARCHAR (500) , 
     ReviewDate DATE NOT NULL , 
     Member_MemberID INTEGER NOT NULL , 
     Facility_FacilityID INTEGER NOT NULL 
    )
GO

ALTER TABLE Review ADD CONSTRAINT Review_PK PRIMARY KEY CLUSTERED (ReviewID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Sport 
    (
     SportID INTEGER NOT NULL , 
     SportName VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Sport ADD CONSTRAINT Sport_PK PRIMARY KEY CLUSTERED (SportID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityID
    ) 
    REFERENCES Facility 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_Member_FK FOREIGN KEY 
    ( 
     Member_MemberID
    ) 
    REFERENCES Member 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FacilityAmenity 
    ADD CONSTRAINT FacilityAmenity_Amenity_FK FOREIGN KEY 
    ( 
     Amenity_AmenityID
    ) 
    REFERENCES Amenity 
    ( 
     AmenityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FacilityAmenity 
    ADD CONSTRAINT FacilityAmenity_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityID
    ) 
    REFERENCES Facility 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FacilitySport 
    ADD CONSTRAINT FacilitySport_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityID
    ) 
    REFERENCES Facility 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FacilitySport 
    ADD CONSTRAINT FacilitySport_Sport_FK FOREIGN KEY 
    ( 
     Sport_SportID
    ) 
    REFERENCES Sport 
    ( 
     SportID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Inquiry 
    ADD CONSTRAINT Inquiry_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityID
    ) 
    REFERENCES Facility 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MemberSports 
    ADD CONSTRAINT MemberSports_Member_FK FOREIGN KEY 
    ( 
     Member_MemberID
    ) 
    REFERENCES Member 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MemberSports 
    ADD CONSTRAINT MemberSports_Sport_FK FOREIGN KEY 
    ( 
     Sport_SportID
    ) 
    REFERENCES Sport 
    ( 
     SportID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingID
    ) 
    REFERENCES Booking 
    ( 
     BookingID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Review 
    ADD CONSTRAINT Review_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityID
    ) 
    REFERENCES Facility 
    ( 
     FacilityID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Review 
    ADD CONSTRAINT Review_Member_FK FOREIGN KEY 
    ( 
     Member_MemberID
    ) 
    REFERENCES Member 
    ( 
     MemberID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             1
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
